
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 09 19:35:30 CEST 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 5;
  public static final int TANTQUE = 30;
  public static final int CROFER = 13;
  public static final int CONSTANTECHAINE = 38;
  public static final int MULT = 16;
  public static final int EGAL = 25;
  public static final int REPETER = 31;
  public static final int SI = 26;
  public static final int SYM_RET = 6;
  public static final int VIRGULE = 9;
  public static final int FIN = 4;
  public static final int LONGUEUR = 35;
  public static final int SYM_PROG = 2;
  public static final int OU = 23;
  public static final int TYPE = 36;
  public static final int INF = 19;
  public static final int NON = 24;
  public static final int PAROUV = 10;
  public static final int DIV = 17;
  public static final int EGALEGAL = 20;
  public static final int SYM_ECRIRE = 33;
  public static final int PLUS = 14;
  public static final int DEBUT = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOINS = 15;
  public static final int ET = 22;
  public static final int IDF = 37;
  public static final int SINON = 28;
  public static final int ALORS = 27;
  public static final int PARFER = 11;
  public static final int CONSTANTEINT = 39;
  public static final int SYM_LIRE = 34;
  public static final int CONSTANTEBOOL = 40;
  public static final int POINT = 7;
  public static final int CROOUV = 12;
  public static final int POINTVIRGULE = 8;
  public static final int FINTANTQUE = 32;
  public static final int SUP = 18;
  public static final int DIFF = 21;
  public static final int FINSI = 29;
}

